- configuration/running-on-boot.md
systemd is the default init system for most modern distros and should be preferred over crontabs and SysVinit
I included a simple service file for a teamspeak 3 server that can be easily adopted to other servers as well
> Include systemd documentation for run on boot

- commands/fastdl.md
CS:GO with Panorama now supports SVG custom logos, which are displayed in more places than a PNG logo.
> FastDL SVG support

- game-servers/ark-survival-evolved.md
If copypasted like most will do, they will get a `cant find pane arkserver` error on boot, this fixes that
> Added quotes to fix boot errors

- game-servers/teamspeak-3.md
Update docs for issue from here:
GameServerManagers/LinuxGSM#2436
Solution from:
https://forum.teamspeak.com/threads/93623-Instance-check-error-failed-to-register-local-accounting-service-on-Linux?p=465663#post465663
> teamspeak 3 - add known issue

- configuration/running-on-boot.md
see top-answer of https://unix.stackexchange.com/questions/137028/why-is-my-systemd-unit-loaded-but-inactive-dead
systemclt shall watch the child-process of "ts3server start", not "ts3server" itself.
> type=forking, not: type=simple

- steamcmd/branch.md
https://github.com/GameServerManagers/LinuxGSM/pull/2532
password protected branch support are removed as its usefulness are very limited and i never heard someone using it
> Update branch parameter

- requirements/jq.md
CentOS 7 got a update for jq recently (epel repo)
Update link form fedora system: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2020-ec6f2e57cb
> fix: jq update centos 7

- alerts/README.md
Removed postdays and posttarget from the more info example as these options are no longer valid due to the postdetails command being hardcoded to use termbin
> Removed postdays and posttarget

- game-servers/arma-3.md
This fixed for me the issue, see: 
https://community.bistudio.com/wiki/Arma_3:_Dedicated_Server#Port_Forwarding
"2306 (BattlEye traffic, +4)"
Maybe its also nice to add it to `./arma3server details` ports section?
> docs: added arma3 troubleshooting section with "BattlEye initialization failed" solution

- requirements/gamedig.md
Update documentation to use NodeJS 16.x due to end of life for 15.x:
```
Node.js 15.x is no longer actively supported!
You will not receive security or critical stability updates for this version.
You should migrate to a supported version of Node.js as soon as possible.
Use the installation script that corresponds to the version of Node.js you
wish to install. e.g.
* https://deb.nodesource.com/setup_12.x — Node.js 12 LTS "Erbium"
* https://deb.nodesource.com/setup_14.x — Node.js 14 LTS "Fermium" (recommended)
* https://deb.nodesource.com/setup_16.x — Node.js 16 "Gallium"
Please see https://github.com/nodejs/Release for details about which
version may be appropriate for you.
The NodeSource Node.js distributions repository contains
information both about supported versions of Node.js and …
```
> Update documentation to use NodeJS 16.x

- guides/security.md
Figured this would add credibility to the method, as well as inform more about what the command does and how to keep select users the ability to list all processes.
> Added a website as source to the hidepid trick

- game-servers/ark-survival-evolved.md
Adding LostIsland to the official ARK map names
> docs: add LostIsland official map name

- game-servers/arma-3.md
Server does not like when the \ is not used in this instance, it is important to not forget.
> docs: Update arma-3.md with more information

- game-servers/counter-strike-global-offensive.md
Add more game modes to the table, and provide values for gamemodeflags and skirmishid (introduced by GameServerManagers/LinuxGSM#4005)
Since this repo doesn't seem to contain the `hacktoberfest` tag, I'd much appreciate it, if you'd add the `hacktoberfest-accepted` label if you approve of this PR
> docs(csgo): extend game mode documentation

- configuration/running-on-boot.md
Having this comment on the same line as the setting causes this service to fail on most systemctl distros. I moved it to its own line.
> Fixed same-line commenting

- game-servers/call-of-duty-4.md
cod4x.me changed its domain to cod4x.ovh. `source` link removed as the forum thread no longer exists and I couldn't find it on the new domain
> Updated dead links

- steamcmd/lan-discovery.md
I was looking for fixes, but no one mentioned this. So I'am adding it to the docs. Originally I found it here: https://github.com/GameServerManagers/LinuxGSM-Docker/issues/4
> Update lan-discovery.md: disable virtual network

- requirements/gamedig.md
Replaces the link reference to the node-GameDig repository to the actual one.
The link redirects to the actual repository, but this is just a tidy small change to be up to date with it :)
Have made the same replacement in [LinuxGSM#4338](https://github.com/GameServerManagers/LinuxGSM/pull/4338), also mentioned that the same link occurs once here.
> docs: replace old node-gamedig link reference to actual repo

- commands/send.md
Hi there!
I run a minecraft server with linuxgsm and I wanted to let my players know that the server would restart 5 mins before it actually would. I searched the docs and there wasn't anything in there that would allow me to do that, so I was going to open an issue in the main repository. After searching through closed issues I found some references to a `send` command, that seemed undocumented.
I thought it best to write some barebones documentation for the command so that people at least know that it exists. I welcome any feedback that you have about the documentation I've written, but hopefully someone with better knowledge of linuxgsm can make this barebones documentation better,
> Added documentation for send command

- game-servers/trackmania-forever.md
As Discussed in [this PR](https://github.com/GameServerManagers/LinuxGSM/pull/4184) TMNF Server hosting needs some documentation. This PR provides all Information of hosting an Internet / LAN Server for TMNF / TMUF. 
Gamemode details will be added in a different PR
> Adding TMNF / TMUF Documentation for Server Hosting
